### PR TITLE
Fix iteration for SparsePolynomial

### LINKED ISSUE #404: Bug in sparse polynomial iteration
```julia
julia> using Polynomials

julia> p = SparsePolynomial([0,1])
SparsePolynomial(x)

julia> collect(p)
2-element Vector{Int64}:
               1
 140175259980384
```

This happens because
```julia
julia> length(p)
2

julia> for (ind, i) in enumerate(p)
       @show ind, i
       end
(ind, i) = (1, 1)
```

### PR DESCRIPTION
**Pull request by jishnub**
This PR does two main things:
1. Change `firstindex`, `lastindex` and `eachindex` for `SparsePolynomial`s to use the default fallback methods. This fixes #404.
2. Change `PolynomialKeys` and `PolynomialValues` to subtype `AbstractSet`, which, in the latter's case, involves adding a type-parameter. This makes empty `SparsePolynomial`s work correctly by fetching the `eltype` from the parent type.

After this PR:
```julia
julia> p = SparsePolynomial([0])
SparsePolynomial(0)

julia> collect(p) # errors on master
Int64[]

julia> p = SparsePolynomial([0,1]) #404
SparsePolynomial(x)

julia> collect(p)
2-element Vector{Int64}:
 0
 1

```

Aside from this, there are some clean-ups of the iteration functions, an optimized `length` method for `SparsePolynomial` and fix some tests. Finally, change `==` checks for `nothing` to `===`, which is the recommended style.

While the changes are largely bug-fixes, I've bumped the minor version as there are some technically breaking changes.

### CODE REVIEW

File: src/polynomials/SparsePolynomial.jl [hunk 1]
```diff
@@ -146,7 +141,7 @@ function Base.iterate(v::PolynomialValues{SparsePolynomial{T,X}}, state...) wher
     return (y[1][2], y[2])
 end
 
-
+Base.length(S::SparsePolynomial) = isempty(S.coeffs) ? 0 : maximum(keys(S.coeffs)) + 1
```
Comment (jverzani) [inline src/polynomials/SparsePolynomial.jl:144]: Yes, I'm glad you caught this. The default realized all the terms!
